// <auto-generated />
using System;
using CardakRezervasyon.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardakRezervasyon.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703055807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.BakimKapaliGun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MesireAlaniId")
                        .HasColumnType("int");

                    b.Property<string>("Sebep")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MesireAlaniId");

                    b.ToTable("BakimKapaliGunler");
                });

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.Cardak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Blok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<bool>("MangalliMi")
                        .HasColumnType("bit");

                    b.Property<int>("MesireAlaniId")
                        .HasColumnType("int");

                    b.Property<int>("Numara")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MesireAlaniId", "AktifMi");

                    b.HasIndex("MesireAlaniId", "Numara")
                        .IsUnique();

                    b.ToTable("Cardaklar");
                });

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.MesireAlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("AcilisSaati")
                        .HasColumnType("time");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("KapanisSaati")
                        .HasColumnType("time");

                    b.Property<string>("Mahalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MesireAlanlari");
                });

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.Rezervasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("CardakId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Not")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("VatandasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VatandasId");

                    b.HasIndex("CardakId", "BaslangicZamani", "BitisZamani");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.Vatandas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vatandaslar");
                });

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.BakimKapaliGun", b =>
                {
                    b.HasOne("CardakRezervasyon.Api.Models.Entities.MesireAlani", "MesireAlani")
                        .WithMany()
                        .HasForeignKey("MesireAlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MesireAlani");
                });

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.Cardak", b =>
                {
                    b.HasOne("CardakRezervasyon.Api.Models.Entities.MesireAlani", "MesireAlani")
                        .WithMany("Cardaklar")
                        .HasForeignKey("MesireAlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MesireAlani");
                });

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.Rezervasyon", b =>
                {
                    b.HasOne("CardakRezervasyon.Api.Models.Entities.Cardak", "Cardak")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("CardakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardakRezervasyon.Api.Models.Entities.Vatandas", "Vatandas")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("VatandasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cardak");

                    b.Navigation("Vatandas");
                });

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.Cardak", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.MesireAlani", b =>
                {
                    b.Navigation("Cardaklar");
                });

            modelBuilder.Entity("CardakRezervasyon.Api.Models.Entities.Vatandas", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
